model_config:
  hf_id: 'TheBloke/phi-2-GGUF'
  hf_file: 'phi-2.Q5_K_S.gguf'
  n_threads: 2
  n_batch: 512
  n_gpu_layers: -1
  n_ctx: 2048
  system_prompt: false
  system_prompt_start_token: "Instruct: "
  system_prompt_end_token: "\n"
  user_prompt_start_token: "Instruct: "
  user_prompt_end_token: "\nOutput:"
  user_followup_prompt_start_token: "Instruct: "
  user_followup_prompt_end_token: "\nOutput:"
  assistant_prompt_start_token: ""
  assistant_prompt_end_token: "\n"
  assistant_followup_prompt_start_token: ""
  assistant_followup_prompt_end_token: "\n"
  end_tokens: 
  - "Instruct:"
  - "Output:"
  verbose: true
  default_completion_config:
    max_tokens: 2048
    temperature: 0.0
    repeat_penalty: 1.1
    echo: false
    top_p: 1
