name: Build macOS with Apple Silicon Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          # lfs: true
          token: ${{ secrets.LLS_CICD }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.13

    - name: Install dependencies
      run: |
        pip install llama-cpp-python==0.2.74 --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
        pip install -r requirements.txt
        pip install pyinstaller==5.13.2

    - name: Build with PyInstaller
      run: pyinstaller app.spec

    - name: Zip the build
      run: zip -r ./LLS-darwin-arm64-$(cat ./version.txt).zip ./dist/app/

    - name: Read version from file
      id: version
      run: |
        echo "VERSION=$(cat ./version.txt)" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.LLS_CICD }}
      with:
        tag_name: darwin-arm64-${{ env.VERSION }}
        release_name: Release of LLS-darwin-arm64-${{ env.VERSION }}
        body: Release of LLS-darwin-arm64-${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.LLS_CICD }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LLS-darwin-arm64-${{ env.VERSION }}.zip
        asset_name: LLS-darwin-arm64-${{ env.VERSION }}.zip
        asset_content_type: application/zip
