name: Update Version Number

on:
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Necessary to enable history for the branch

      - name: Read the current version
        id: current_version
        run: |
          echo "Current_Version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Update the version number
        run: |
          IFS='.' read -ra VERSION <<< "${{ env.Current_Version }}"
          VERSION[2]=$((${VERSION[2]} + 1))
          NEW_VERSION="${VERSION[0]}.${VERSION[1]}.${VERSION[2]}"
          echo $NEW_VERSION > version.txt
          echo "New_Version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add version.txt
          git commit -m "Update version number to ${{ env.New_Version }}"
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.LLS_CICD }}@github.com/${{ github.repository }}
          git push
